### ISSUE TITLE
Redesign&Rename item_header

### ISSUE THREAD

**Issue by YuChocopie** [chatty-app/chatty-app#25]
- item_header.xml 의 이름을 item_my_partner로 변경
- ConstraintLayout 을 사용하여 디자인 수정

**Comment by eldenpark** [comment]
issue 는 가급적 자연어 문법을 준수하여 작성해주시면 좋을 것 같습니다. `Redesign and rename item_header` 면 더 좋을 것 같습니다. @dbwjd
